django_project/App_Login/urls.py
from django.urls path 
app_name = 'App_Login'




urlpatterns = [

]

django_project/App_Shop/urls.py
from django.urls path 
app_name = 'App_Shop'




urlpatterns = [
    
]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

django_project/App_Login/models.py
from django.db import models

# to create custom user model and admin panel

from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin,
PermissionsMixin
from django.utils.translation import ugettext, ugettext_lazy.lazy

# Create your models here.
class MyUserManager(BaseUserManager):
    """Its a custom manaer that deals emails as unique identifier"""
    def _create_user(self,email,password,**extra_fields):
        """Creates and saves user with given email and password"""

        if not email:
            raise ValueError("The email must be set!")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,email,password,**extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True) 

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is-staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    is_staff = models.BooleanField(
        ugettext_lazy('staff status'),
        default=False,
        half_text = ugettext_lazy('Designates whether the user can log in this site')
    )

    is_active = models.BooleanField{
        ugettext_lazy('active'),
        default=True,
        help_text=ugettext_lazy('Designated whether this user should be treated as active. Unselect this instead of deleting accounts')
    }

    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email


class Profile (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=264, blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    address_1 = models.TextField(max_length=300, blank=True)
    city = models.CharField(max_length=40, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    

django_project/App_Shop/models.py
from django.db import models

# Create your models here.

django_project/App_Login/views.py
from django.shortcuts import render

# Create your views here.

django_project/App_Shop/views.py
from django.shortcuts import render

# Create your views here.

django_project/templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Profile {% endblock %}
{% block body_block %}
<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" class="btn btn-warning btn-sm">Save</button>
</form>
<br>
<br>
{% endblock %}

django_project/templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block body_block %}
<h2>Login:</h2>
<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" class="btn btn-primary btn-sm">Login</button>
</form>
<br>
<p>Doesn't have an account? <a href="{% url 'App_Login:signup' %}">Create New Account</a></p>
{% endblock %}

django_project/templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %}
{% block body_block %}
<h2>Create New Account:</h2>
<form method="POST">
{{ form|crispy }}
{% csrf_token %}
<button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br>
<p>Already have an account? <a href="{% url 'App_Login:login' %}">Login Here</a></p>
{% endblock %}

django_project/templates/App_Order/cart.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
  <div class="my-5">
    <h2>Your Cart</h2>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col" width="15%">#</th>
        <th scope="col">Product Name</th>
        <th scope="col">Quantity</th>
        <th scope="col" align="right">Price</th>
        <th scop="col">Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for cart in carts %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{cart.item.name}}</td>
        <td>
          <a class="mr-2" href="{% url 'App_Order:decrease' pk=cart.item.pk %}"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
          {{ cart.quantity }}
          <a class="mr-2" href="{% url 'App_Order:increase' pk=cart.item.pk %}"> <span class="badge badge-light"> <i class="fas fa-plus"></i></span></a>
        </td>
        <td align="right">&#2547; {{cart.get_total}}</td>
        <td><a href="{% url 'App_Order:remove' pk=cart.item.pk %}" class="btn btn-danger btn-sm">Remove From Cart</a></td>
      </tr>
      {% endfor %}
      <tr>
        <th scope="row"></th>
        <td colspan="2">Total</td>
        <td align="right">&#2547; {{order.get_totals | floatformat:2 }}</td>
        <td></td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td colspan="4" class="text-right">
          <a href="{% url 'App_Shop:home' %}" class="btn btn-warning mr-4">Continue Shoping</a>
          <a href="{% url 'App_Payment:checkout' %}" class="btn btn-success mr-4">Proceed To Checkout</a>
        </td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

django_project/templates/App_Shop/home.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
  <h2 class="my-5">Featured Products</h2>
  <div class="row">
    {% for product in object_list %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"><a href="{% url 'App_Shop:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

django_project/templates/App_Shop/product_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
  <div class="card">
    <div class="row">
      <aside class="col-sm-5 border-right">
        <article class="gallery-wrap">
          <div class="img-big-wrap">
            <div>
              <a href="#"><img src="/media/{{object.mainimage}}" style="width:450px"></a>
            </div>
          </div>
        </article>
      </aside>
      <aside class="col-sm-7">
        <article class="card-body p-5">
          <h3 class="title mp-3">{{object.name}}</h3>
          <p class="price-detail-wrap">
            <span class="price h3 text-warning">
              <span class="currency">BDT &#2547;</span><span class="num">{{object.price}}</span>
            </span>
          </p>
          <dl class="item-property">
            <dt>Description</dt>
            <dd>
              <p>{{object.detail_text|linebreaks}}</p>
            </dd>
          </dl>
          <a href="{% url 'App_Order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"> <i class="fas fa-shopping-cart"></i> Add to Cart</a>
        </article>
      </aside>
    </div>
  </div>
</div>
{% endblock %}

django_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>{% block title_block %} E-com | Bohubrihi {% endblock %}</title>
  <style>
  .card {
    height: 350px;
  }

  .card-product:after {
    content: "";
    display: table;
    clear: both;
    visibility: hidden;
  }
  .card-product .price-new, .card-product .price {
    margin-right: 5px;
  }

  .card-product .price-old {
    color: #999;
  }

  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;
    overflow: hidden;
    position: relative;
    height: 220px;
    text-align: center;
  }

  .card-product .img-wrap img {
    max-height: 100%;
    max-width: 100%;
    object-fit: cover;
  }

  .card-product .info-wrap {
    overflow: hidden;
    padding: 15px;
    border-top: 1px solid #eee;
  }

  .card-product .action-wrap {
    padding-top: 4px;
    margin-top: 4px;
  }

  .card-product .bottom-wrap {
    padding: 15px;
    border-top: 1px solid #eee;
  }

  .card-product .title {
    margin-top: 0px;
  }

  </style>
</head>
<body>
  {% include 'navbar.html' %}
  <div class="container">
    <div class="messages container mt-2">
      {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    {% block body_block %} {% endblock %}

  </div>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

django_project/templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'App_Shop:home' %}">Django E-commerce Project</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'App_Order:cart' %}" class="nav-link">
              <i class="fa fa-shopping-cart"></i> Cart
              <span class="badge badge-light">{{ request.user | cart_total }}</span>
          </a>
        </li>
        <li class="nav-item">

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i> {{request.user.profile.username}}</a>
          <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
            <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'App_Payment:orders' %}">Orders</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'App_Login:login' %}" class="btn btn-primary">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>